Repository sony/nnabla-examples, pull requests merged in 2019-05, with the labels that each got.

#85 Synchronized Batch Normalization
  distributed/cifar10-100/args.py
  distributed/cifar10-100/models.py
  distributed/cifar10-100/multi_device_multi_process_classification.py
Labels: enhancement

#87 Align the latest changes of DALI pkg
  imagenet-classification/dali_data_iterator.py
Labels: enhancement

#91 Enabled non square input size in DeepLabV3+ example
  semantic-segmentation/deeplabv3plus/eval.py
  semantic-segmentation/deeplabv3plus/image_preprocess.py
  semantic-segmentation/deeplabv3plus/model.py
  semantic-segmentation/deeplabv3plus/model_inference.py
  semantic-segmentation/deeplabv3plus/segmentation_data.py
  semantic-segmentation/deeplabv3plus/train.py
Labels: release-note-examples

#92 delete unused arguments and specified allow_pickle=True explicitly
  GANs/pix2pix/facade.py
  NAS/DARTS/cifar10_data.py
  NAS/ENAS/cifar10_data.py
  NAS/ENAS/macro_retrain.py
  NAS/ENAS/micro_retrain.py
  cifar10-100-collection/cifar100_data.py
  cifar10-100-collection/cifar10_data.py
  distributed/cifar10-100/cifar100_data.py
  distributed/cifar10-100/cifar10_data.py
  meta-learning/metric_based_meta_learning.py
  mnist-collection/mnist_data.py
  mnist-collection/siamese.py
  parametric_function_classes/mnist-collection/mnist_data.py
  reduction/cifar10/distillation/cifar10_data.py
  reduction/cifar10/factorized-layers/cifar10_data.py
  reduction/cifar10/quantization/cifar10_data.py
  reduction/cifar10/resnet2rnn/cifar10_data.py
  reduction/cifar10/shiftnet/cifar10_data.py
  reduction/cifar10/shufflenet/cifar10_data.py
  reduction/cifar10/structured-sparsity/cifar10_data.py
  reduction/mnist/svd/mnist_data.py
  semantic-segmentation/deeplabv3plus/segmentation_data.py
  speech-synthesis/WaveNet/dataset.py
Labels: release-note-ignore
