Repository sony/nnabla-examples, pull requests merged in 2020-10, with the labels that each got.

#171 Add Pre-trained Parameters for MUNIT
  GANs/munit/README.md
Labels: release-note-examples

#172 Fix regex error in mixup script for ImageNet classification
  imagenet-classification/utils/mixup.py
Labels: release-note-bugfix

#173 update Dockerfile
  Dockerfile
Labels: release-note-bugfix

#174 Fixed multiple download issue on multinode training
  distributed/cifar10-100/multi_device_multi_process_classification.py
Labels: release-note-ignore
