Repository sony/nnabla-examples, pull requests merged in 2020-04, with the labels that each got.

#142 SPADE
  GANs/pix2pixHD/models.py
  GANs/pix2pixHD/trainer.py
  GANs/pix2pixHD/utils.py
  GANs/spade/.gitignore
  GANs/spade/README.md
  GANs/spade/config.yaml
  GANs/spade/generate.py
  GANs/spade/imgs/ade20k_input1.jpg
  GANs/spade/imgs/ade20k_input2.jpg
  GANs/spade/imgs/ade20k_output1.jpg
  GANs/spade/imgs/ade20k_output2.jpg
  GANs/spade/imgs/cityscapes_input1.jpg
  GANs/spade/imgs/cityscapes_input2.jpg
  GANs/spade/imgs/cityscapes_output1.jpg
  GANs/spade/imgs/cityscapes_output2.jpg
  GANs/spade/models.py
  GANs/spade/pretrained_model/ade20k/config.yaml
  GANs/spade/pretrained_model/cityscapes/config.yaml
  GANs/spade/requirements.txt
  GANs/spade/scripts/mgpu_train_ade20k.sh
  GANs/spade/scripts/mgpu_train_cityscapes.sh
  GANs/spade/scripts/train_ade20k.sh
  GANs/spade/scripts/train_cityscapes.sh
  GANs/spade/train.py
  GANs/spade/utils.py
  utils/neu/comm.py
  utils/neu/datasets/__init__.py
  utils/neu/datasets/ade20k.py
  utils/neu/datasets/city_scapes.py
  utils/neu/initializer.py
  utils/neu/layers.py
  utils/neu/lr_scheduler.py
  utils/neu/misc.py
Labels: release-note-examples

#143 Fix ImageNet classification training example due to merge conflict
  utils/neu/comm.py
  utils/neu/misc.py
Labels: release-note-bugfix

#144 MobileNet V1, V2, and V3
  doc/docker.md
  imagenet-classification/README.md
  imagenet-classification/args.py
  imagenet-classification/cfg/cos90.yaml
  imagenet-classification/data.py
  imagenet-classification/models/__init__.py
  imagenet-classification/models/efficientnet.py
  imagenet-classification/models/mobilenet.py
  imagenet-classification/train.py
  imagenet-classification/utils/__init__.py
  imagenet-classification/validation.py
  utils/neu/save_args.py
Labels: release-note-examples

#145 Fix auto format issue
  imagenet-classification/models/mobilenet.py
Labels: release-note-ignore
