Repository sony/nnabla-examples, pull requests merged in 2021-09, with the labels that each got.

#241 [XAI] Update responsible_ai README
  responsible_ai/README.md
Labels: release-note-ignore

#245 [XAI] Grad-CAM Colab revised
  .DS_Store
  interactive-demos/.DS_Store
  interactive-demos/gradcam.ipynb
  responsible_ai/data_cleansing/.DS_Store
  responsible_ai/face_evaluation/.DS_Store
  responsible_ai/gradcam/images/grad-cam_fig.png
Labels: release-note-ignore

#244 Add URL for pre-trained weight of deep exemplar-based video colorization
  video-colorization/deep-exemplar-based-video-colorization/README.md
Labels: release-note-examples

#247 [XAI] Kernel SHAP (tabular data)
  responsible_ai/.DS_Store
  responsible_ai/README.md
  responsible_ai/kernel_shap/README.md
  responsible_ai/kernel_shap/calculate.py
  responsible_ai/kernel_shap/images/sample.png
  responsible_ai/kernel_shap/iris_flower_dataset_training_delo.csv
  responsible_ai/kernel_shap/iris_flower_dataset_validation_delo.csv
  responsible_ai/kernel_shap/kernel_shap.py
  responsible_ai/kernel_shap/train.py
  responsible_ai/kernel_shap/visualize.py
Labels: release-note-examples

#248 HiFiGAN implementation
  speech-synthesis/HiFiGAN/README.md
  speech-synthesis/HiFiGAN/dataset.py
  speech-synthesis/HiFiGAN/docker/Dockerfile
  speech-synthesis/HiFiGAN/hparams.py
  speech-synthesis/HiFiGAN/images/hifigan_arch.png
  speech-synthesis/HiFiGAN/main.py
  speech-synthesis/HiFiGAN/model/__init__.py
  speech-synthesis/HiFiGAN/model/model.py
  speech-synthesis/HiFiGAN/model/ops.py
  speech-synthesis/HiFiGAN/preprocess.py
  speech-synthesis/HiFiGAN/requirements.txt
  speech-synthesis/HiFiGAN/synthesize.py
  speech-synthesis/HiFiGAN/train.py
  speech-synthesis/HiFiGAN/utils.py
Labels: enhancement, release-note-examples

#249 add demo about quantized tflite converter
  README.md
  interactive-demos/quantization_tutorial.ipynb
Labels: release-note-examples

#250 fix errors in nnabla examples
  GANs/stargan/args.py
  NAS/ENAS/README.md
  meta-learning/prototypical/prototypical.py
Labels: release-note-bugfix
