Repository sony/nnabla-examples, pull requests merged in 2021-11, with the labels that each got.

#262 Pointnet for 3d object classification implementation
  3d-object-classification/pointnet/README.md
  3d-object-classification/pointnet/data/__init__.py
  3d-object-classification/pointnet/data/data_utils.py
  3d-object-classification/pointnet/data/download_data.sh
  3d-object-classification/pointnet/data/modelnet40_normal_resampled_dataiter.py
  3d-object-classification/pointnet/evaluate.py
  3d-object-classification/pointnet/loss.py
  3d-object-classification/pointnet/model.py
  3d-object-classification/pointnet/model_utils.py
  3d-object-classification/pointnet/requirements.txt
  3d-object-classification/pointnet/running_utils.py
  3d-object-classification/pointnet/train.py
Labels: release-note-examples

#263 Fix auto format
  3d-object-classification/pointnet/data/modelnet40_normal_resampled_dataiter.py
  3d-object-classification/pointnet/evaluate.py
  3d-object-classification/pointnet/loss.py
  3d-object-classification/pointnet/model.py
  3d-object-classification/pointnet/model_utils.py
  3d-object-classification/pointnet/train.py
Labels: release-note-ignore

#268 Example: Implicit differentiable renderer
  shape-reconstruction/implicit-differentiable-renderer/Dockerfile
  shape-reconstruction/implicit-differentiable-renderer/IDR_workflow.png
  shape-reconstruction/implicit-differentiable-renderer/README.md
  shape-reconstruction/implicit-differentiable-renderer/config/default.yaml
  shape-reconstruction/implicit-differentiable-renderer/dataset.py
  shape-reconstruction/implicit-differentiable-renderer/evaluate.py
  shape-reconstruction/implicit-differentiable-renderer/extract.py
  shape-reconstruction/implicit-differentiable-renderer/helper.py
  shape-reconstruction/implicit-differentiable-renderer/network.py
  shape-reconstruction/implicit-differentiable-renderer/ray_tracer.py
  shape-reconstruction/implicit-differentiable-renderer/requirements.txt
  shape-reconstruction/implicit-differentiable-renderer/sdf_contour_D512_L009.png
  shape-reconstruction/implicit-differentiable-renderer/synthesize.py
  shape-reconstruction/implicit-differentiable-renderer/test_postmethod.py
  shape-reconstruction/implicit-differentiable-renderer/train.py
Labels: release-note-examples

#267 auto-format-update
  GANs/first-order-model/animate.py
  GANs/first-order-model/reconstruct.py
  GANs/first-order-model/train.py
  GANs/reenactgan/data.py
  GANs/reenactgan/preprocess.py
  GANs/reenactgan/test_reenactment.py
  GANs/reenactgan/train_decoder.py
  GANs/reenactgan/train_transformer.py
  GANs/stylegan2-distillation/data_generation.py
  GANs/stylegan2-distillation/generate_attribute_direction.py
  GANs/stylegan2/generate.py
  GANs/stylegan2/networks.py
  imagenet-classification/infer.py
  imagenet-classification/validation.py
  object-detection/centernet/src/lib/tools/voc_eval_lib/nms/cpu_nms.c
  object-detection/centernet/src/lib/tools/voc_eval_lib/nms/gpu_nms.cpp
  responsible_ai/adversarial_debiasing/utils.py
  responsible_ai/data_cleansing/eval_influence_functions.py
  responsible_ai/data_cleansing/eval_sgd_influence.py
  responsible_ai/kernel_shap/calculate.py
  responsible_ai/three_metrics/utils.py
  responsible_ai/tracin/mislabel_analysis.py
  speech-synthesis/TTS/tacotron/model/ops.py
  speech-synthesis/TTS/tacotron/train.py
  speech-synthesis/TTS/tacotron2/train.py
  speech-synthesis/WaveGlow/model/model.py
  speech-synthesis/WaveGlow/train.py
  utils/neu/metrics/gan_eval/fid.py
  utils/neu/metrics/gan_eval/inception_score.py
  utils/neu/metrics/lpips/compute.py
  utils/neu/misc.py
  video-colorization/deep-exemplar-based-video-colorization/inference.py
Labels: release-note-ignore

#269 add file_format_converter.ipynb
  interactive-demos/file_format_converter.ipynb
Labels: release-note-examples

#270 Add demonstration for format converter and ONNX Runtime Web.
  format-converter/ORT-Web/README.md
  format-converter/ORT-Web/convert-resnet50.sh
  format-converter/ORT-Web/html/imagenet_labels.js
  format-converter/ORT-Web/html/regression.html
  format-converter/ORT-Web/html/resnet50.html
Labels: release-note-examples

#271 use basename if yaml filename is absolute path.
  utils/neu/save_args.py
Labels: release-note-bugfix

#273 format for latest nnabla-examples
  GANs/stylegan2-cdc/execution/evaluate.py
  GANs/stylegan2-cdc/execution/ops.py
  GANs/stylegan2-cdc/execution/train.py
  GANs/stylegan2-cdc/models/__init__.py
  GANs/stylegan2-cdc/models/discriminators.py
  GANs/stylegan2-cdc/models/generators.py
  GANs/stylegan2-cdc/models/networks.py
  GANs/stylegan2-cdc/models/ops.py
  GANs/stylegan2-cdc/models/patch_discriminators.py
  GANs/stylegan2-ewc/execution/evaluate.py
  GANs/stylegan2-ewc/execution/ops.py
  GANs/stylegan2-ewc/execution/train.py
  GANs/stylegan2-ewc/models/networks.py
  GANs/tecogan/generate.py
  responsible_ai/rejection_option_based_classification/utils.py
  shape-reconstruction/implicit-differentiable-renderer/helper.py
  shape-reconstruction/implicit-differentiable-renderer/ray_tracer.py
  shape-reconstruction/implicit-differentiable-renderer/synthesize.py
Labels: release-note-ignore

#274 Modified loss function with lpips and added scripts for interpolation and style mixing
  GANs/slegan/README.md
  GANs/slegan/generator.py
  GANs/slegan/interpolate.py
  GANs/slegan/loss.py
  GANs/slegan/lpips.py
  GANs/slegan/stylemix.py
Labels: release-note-examples

#275 fix device_id value and use built flatc
  interactive-demos/quantization_tutorial.ipynb
Labels: release-note-ignore
