Repository sony/nnabla-examples, pull requests merged in 2021-04, with the labels that each got.

#211 remove conda from dockerfile
  Dockerfile
Labels: release-note-examples

#210 Format changed
  responsible_ai/data_cleansing/datasets/create_cifar10_csv.py
  responsible_ai/data_cleansing/datasets/create_mnist_csv.py
  responsible_ai/data_cleansing/datasets/create_stl10_csv.py
  responsible_ai/data_cleansing/datasets/utils.py
  responsible_ai/data_cleansing/sgd_influence/analyze.py
  responsible_ai/data_cleansing/sgd_influence/dataset.py
  responsible_ai/data_cleansing/sgd_influence/eval.py
  responsible_ai/data_cleansing/sgd_influence/infl.py
  responsible_ai/data_cleansing/sgd_influence/model.py
  responsible_ai/data_cleansing/sgd_influence/train.py
  responsible_ai/data_cleansing/sgd_influence/utils.py
  responsible_ai/data_cleansing/train_infl_eval.py
Labels: release-note-ignore

#212 fix animate script and replace the result + minor correction
  GANs/first-order-model/animate.py
  GANs/first-order-model/imgs/sample_fake.gif
  interactive-demos/fomm.ipynb
Labels: release-note-bugfix

#213 Grad-CAM/eXplainable AI
  README.md
  interactive-demos/gradcam.ipynb
  responsible_ai/gradcam/README.md
  responsible_ai/gradcam/gradcam.py
  responsible_ai/gradcam/images/sample.png
Labels: release-note-examples

#214 fix tecogan argument type and its default value
  GANs/tecogan/README.md
  GANs/tecogan/args.py
  GANs/tecogan/config.yaml
Labels: release-note-ignore

#215 Use urllib instead of requests
  GANs/pix2pix/facade.py
Labels: release-note-ignore
