Repository sony/nnabla-examples, pull requests merged in 2021-12, with the labels that each got.

#276 ImageNet classification finetuning sample
  Dockerfile
  imagenet-classification/README.md
  imagenet-classification/args.py
  imagenet-classification/cfg/finetune10.yaml
  imagenet-classification/create_caltech101_dataset.py
  imagenet-classification/train.py
Labels: release-note-examples

#277 Add improved DDPM example
  diffusion-models/.gitignore
  diffusion-models/README.md
  diffusion-models/config.py
  diffusion-models/dataset/__init__.py
  diffusion-models/dataset/cifar10.py
  diffusion-models/dataset/common.py
  diffusion-models/dataset/imagenet.py
  diffusion-models/diffusion.py
  diffusion-models/generate.py
  diffusion-models/imgs/celebahq.png
  diffusion-models/imgs/cifar10.png
  diffusion-models/imgs/imagenet64x64.png
  diffusion-models/layers.py
  diffusion-models/model.py
  diffusion-models/requirements.txt
  diffusion-models/scripts/train_celebahq.sh
  diffusion-models/scripts/train_cifar10.sh
  diffusion-models/scripts/train_imagenet.sh
  diffusion-models/scripts/train_imagenet64x64.sh
  diffusion-models/train.py
  diffusion-models/unet.py
  diffusion-models/utils.py
  setup.py
  utils/.gitignore
  utils/README.md
  utils/neu/checkpoint_util.py
  utils/neu/cli.py
  utils/neu/comm.py
  utils/neu/datasets/__init__.py
  utils/neu/losses.py
  utils/neu/metrics/gan_eval/fid.py
  utils/neu/metrics/gan_eval/inception_score.py
  utils/neu/misc.py
  utils/neu/reporter.py
  utils/neu/yaml_wrapper.py
Labels: release-note-examples

#280 Fix ResNet base comments
  imagenet-classification/models/base.py
Labels: release-note-doc

#281 correct example format
  GANs/stylegan2-training/execution/evaluate.py
  GANs/stylegan2-training/execution/ops.py
  GANs/stylegan2-training/execution/train.py
  GANs/stylegan2-training/models/networks.py
Labels: release-note-ignore

#283 correct examples format
  view-synthesis/nerf/data_iterator/get_data.py
  view-synthesis/nerf/data_iterator/make_tsv.py
  view-synthesis/nerf/data_iterator/photo_tourism.py
  view-synthesis/nerf/train/nerf.py
  view-synthesis/nerf/visualize.py
Labels: release-note-ignore
