Repository sony/nnabla-examples, pull requests merged in 2022-08, with the labels that each got.

#337 [XAI] update eigencam notebook
  interactive-demos/eigencam.ipynb
Labels: release-note-bugfix

#338 Add conditional adm examples
  diffusion-models/.gitignore
  diffusion-models/README.md
  diffusion-models/conf/config_generate.yaml
  diffusion-models/conf/config_train.yaml
  diffusion-models/conf/dataset/celebahq.yaml
  diffusion-models/conf/dataset/cifar10.yaml
  diffusion-models/conf/dataset/imagenet.yaml
  diffusion-models/conf/diffusion/cosine.yaml
  diffusion-models/conf/diffusion/linear.yaml
  diffusion-models/conf/hydra/simple.yaml
  diffusion-models/conf/model/adm_256.yaml
  diffusion-models/conf/model/adm_64.yaml
  diffusion-models/conf/model/adm_64_class_cond.yaml
  diffusion-models/conf/model/adm_64to256_class_cond.yaml
  diffusion-models/conf/model/ddpm_256.yaml
  diffusion-models/conf/model/iddpm_32.yaml
  diffusion-models/conf/model/iddpm_64.yaml
  diffusion-models/conf/runtime/default.yaml
  diffusion-models/conf/train/celebahq_256_ddpm.yaml
  diffusion-models/conf/train/cifar10_iddpm.yaml
  diffusion-models/conf/train/imagenet_256_adm.yaml
  diffusion-models/conf/train/imagenet_64_adm.yaml
  diffusion-models/conf/train/imagenet_64_iddpm.yaml
  diffusion-models/conf/train/imagenet_64to256_adm.yaml
  diffusion-models/config.py
  diffusion-models/dataset/__init__.py
  diffusion-models/dataset/cifar10.py
  diffusion-models/dataset/common.py
  diffusion-models/dataset/imagenet.py
  diffusion-models/diffusion.py
  diffusion-models/generate.py
  diffusion-models/layers.py
  diffusion-models/model.py
  diffusion-models/requirements.txt
  diffusion-models/scripts/ADM_train_imagenet.sh
  diffusion-models/scripts/adm/train_celebahq256x256.sh
  diffusion-models/scripts/adm/train_imagenet256x256.sh
  diffusion-models/scripts/adm/train_imagenet64x64.sh
  diffusion-models/scripts/adm/train_imagenet64x64_class_cond.sh
  diffusion-models/scripts/ddpm/train_celebahq.sh
  diffusion-models/scripts/iddpm/train_cifar10.sh
  diffusion-models/scripts/iddpm/train_imagenet64x64.sh
  diffusion-models/scripts/train_celebahq.sh
  diffusion-models/scripts/train_cifar10.sh
  diffusion-models/scripts/train_imagenet.sh
  diffusion-models/scripts/train_imagenet64x64.sh
  diffusion-models/sdedit.py
  diffusion-models/train.py
  diffusion-models/unet.py
  diffusion-models/utils.py
  utils/neu/mixed_precision.py
Labels: release-note-examples

#339 modify nnabla-examples code format to support new autopep8
  image-superresolution/esrgan/convert_vgg19_weights.py
  object-detection/centernet/src/lib/utils/voc_eval_lib/datasets/pascal_voc.py
  object-detection/yolov2/image.py
  object-detection/yolov2/image2.py
  object-detection/yolov2/utils.py
  object-detection/yolov2/valid.py
  semantic-segmentation/deeplabv3plus/convert_tf_nnabla.py
  semantic-segmentation/deeplabv3plus/xception_65.py
  video-colorization/deep-exemplar-based-video-colorization/preprocess.py
  video-superresolution/tecogan/authors_scripts/dataPrepare.py
  video-superresolution/tecogan/authors_scripts/download_test_data.py
Labels: release-note-ignore

#340 [Fairness] Rejection Option-based classification on image data(part2)
  README.md
  interactive-demos/reject_option_based_classification_images.ipynb
  responsible_ai/README.md
  responsible_ai/rejection_option_based_classification_images/README.md
Labels: release-note-examples

#342 [XAI ]resolve conflict
  README.md
  responsible_ai/README.md
Labels: release-note-bugfix

#343 Fix CelebAHQ config url in DDPM example
  diffusion-models/README.md
Labels: release-note-ignore
